/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReserverRouteImport } from './routes/reserver'
import { Route as ReceptionRouteImport } from './routes/reception'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as HotelRouteImport } from './routes/hotel'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TableTableNumberRouteImport } from './routes/table.$tableNumber'
import { Route as ChambreRoomNumberRouteImport } from './routes/chambre.$roomNumber'

const ReserverRoute = ReserverRouteImport.update({
  id: '/reserver',
  path: '/reserver',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionRoute = ReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelRoute = HotelRouteImport.update({
  id: '/hotel',
  path: '/hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableTableNumberRoute = TableTableNumberRouteImport.update({
  id: '/table/$tableNumber',
  path: '/table/$tableNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ChambreRoomNumberRoute = ChambreRoomNumberRouteImport.update({
  id: '/chambre/$roomNumber',
  path: '/chambre/$roomNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/gallery': typeof GalleryRoute
  '/hotel': typeof HotelRoute
  '/menu': typeof MenuRoute
  '/reception': typeof ReceptionRoute
  '/reserver': typeof ReserverRoute
  '/chambre/$roomNumber': typeof ChambreRoomNumberRoute
  '/table/$tableNumber': typeof TableTableNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/gallery': typeof GalleryRoute
  '/hotel': typeof HotelRoute
  '/menu': typeof MenuRoute
  '/reception': typeof ReceptionRoute
  '/reserver': typeof ReserverRoute
  '/chambre/$roomNumber': typeof ChambreRoomNumberRoute
  '/table/$tableNumber': typeof TableTableNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/gallery': typeof GalleryRoute
  '/hotel': typeof HotelRoute
  '/menu': typeof MenuRoute
  '/reception': typeof ReceptionRoute
  '/reserver': typeof ReserverRoute
  '/chambre/$roomNumber': typeof ChambreRoomNumberRoute
  '/table/$tableNumber': typeof TableTableNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/evenements'
    | '/gallery'
    | '/hotel'
    | '/menu'
    | '/reception'
    | '/reserver'
    | '/chambre/$roomNumber'
    | '/table/$tableNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/evenements'
    | '/gallery'
    | '/hotel'
    | '/menu'
    | '/reception'
    | '/reserver'
    | '/chambre/$roomNumber'
    | '/table/$tableNumber'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/evenements'
    | '/gallery'
    | '/hotel'
    | '/menu'
    | '/reception'
    | '/reserver'
    | '/chambre/$roomNumber'
    | '/table/$tableNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  EvenementsRoute: typeof EvenementsRoute
  GalleryRoute: typeof GalleryRoute
  HotelRoute: typeof HotelRoute
  MenuRoute: typeof MenuRoute
  ReceptionRoute: typeof ReceptionRoute
  ReserverRoute: typeof ReserverRoute
  ChambreRoomNumberRoute: typeof ChambreRoomNumberRoute
  TableTableNumberRoute: typeof TableTableNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reserver': {
      id: '/reserver'
      path: '/reserver'
      fullPath: '/reserver'
      preLoaderRoute: typeof ReserverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception': {
      id: '/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof ReceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel': {
      id: '/hotel'
      path: '/hotel'
      fullPath: '/hotel'
      preLoaderRoute: typeof HotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$tableNumber': {
      id: '/table/$tableNumber'
      path: '/table/$tableNumber'
      fullPath: '/table/$tableNumber'
      preLoaderRoute: typeof TableTableNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chambre/$roomNumber': {
      id: '/chambre/$roomNumber'
      path: '/chambre/$roomNumber'
      fullPath: '/chambre/$roomNumber'
      preLoaderRoute: typeof ChambreRoomNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  EvenementsRoute: EvenementsRoute,
  GalleryRoute: GalleryRoute,
  HotelRoute: HotelRoute,
  MenuRoute: MenuRoute,
  ReceptionRoute: ReceptionRoute,
  ReserverRoute: ReserverRoute,
  ChambreRoomNumberRoute: ChambreRoomNumberRoute,
  TableTableNumberRoute: TableTableNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
